### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by BGriffy78** [ics-software-engineering/meteor-application-template#1]
Not an issue, but a thanks. 

While experienced in developing software, the area of web development is completely new to me. 

I found meteor and have been going through the tutorials. I’m excited to tinker with it. I feel finding this template will really help me get up to speed fast knowing how to structure my project and make it look decent during its development (I’m no front end guy). 

Thanks again!

P.S. I guess I have one quick question...  does your approach favor Blaze or React or is it completely abstracted from either top layer?

**Comment by philipmjohnson** [comment]
Thanks for the kind words.  If you're new to Meteor, you might find my four module series on Meteor (plus one on Mongo) that I use in my software engineering class to be of interest:

http://courses.ics.hawaii.edu/ics314f17/modules/

My approach uses Blaze.  I believe Blaze is much easier to learn than React and better suited to my pedagogy.  React has better modularity than Blaze and complex sharing of state between components is definitely easier. So they both have strengths and weaknesses.
